# Generated by Django 2.0 on 2018-10-12 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_auto_20181009_1634'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('content', models.TextField(verbose_name='评论的内容')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
            },
        ),
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发起时间')),
                ('content', models.TextField(verbose_name='探讨内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户探讨',
                'verbose_name_plural': '用户探讨',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comm2Explore',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='operations.Explore', verbose_name='评论探讨'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comm2hacker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Hacker', verbose_name='评论hacker'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comm2opensource',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Opensource', verbose_name='评论开源'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comm2programming',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Programming', verbose_name='评论编程'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comm2software',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Software', verbose_name='评论软件'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
