# Generated by Django 2.0 on 2018-12-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_comment_comm2hacker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comm2Explore',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comm2opensource',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comm2programming',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comm2software',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Explore',
        ),
    ]
