# Generated by Django 2.0 on 2018-10-01 15:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opensource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('release_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间')),
                ('comment_no', models.IntegerField(verbose_name='评论数')),
                ('like_no', models.IntegerField(verbose_name='点赞数')),
                ('project_addr', models.CharField(max_length=100, verbose_name='项目地址')),
                ('description', models.TextField(verbose_name='软件描述')),
                ('contribute_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='帖子投稿者')),
                ('release_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='帖子发布者')),
            ],
            options={
                'verbose_name': '开源',
                'verbose_name_plural': '开源',
            },
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('release_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间')),
                ('comment_no', models.IntegerField(verbose_name='评论数')),
                ('like_no', models.IntegerField(verbose_name='点赞数')),
                ('type', models.IntegerField(choices=[(1, 'Java'), (2, 'Python')], verbose_name='编程语言')),
                ('description', models.TextField(verbose_name='软件描述')),
                ('contribute_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='帖子投稿者')),
                ('release_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='帖子发布者')),
            ],
            options={
                'verbose_name': '编程语言',
                'verbose_name_plural': '编程语言',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('release_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间')),
                ('comment_no', models.IntegerField(verbose_name='评论数')),
                ('like_no', models.IntegerField(verbose_name='点赞数')),
                ('icon', models.ImageField(upload_to='media/software/icon/%Y/%m', verbose_name='软件icon')),
                ('type', models.IntegerField(choices=[(1, 'Windows'), (2, 'Android'), (3, 'IOS'), (4, 'MAC'), (5, 'Linux')], verbose_name='软件分类')),
                ('description', models.TextField(verbose_name='软件描述')),
                ('contribute_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='帖子投稿者')),
                ('release_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='帖子发布者')),
            ],
            options={
                'verbose_name': '软件',
                'verbose_name_plural': '软件',
            },
        ),
    ]
