# Generated by Django 2.0 on 2018-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming',
            name='comment_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='programming',
            name='like_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
    ]
