# Generated by Django 2.0 on 2018-12-21 02:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('release_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间')),
                ('comment_no', models.IntegerField(blank=True, null=True, verbose_name='评论数')),
                ('like_no', models.IntegerField(blank=True, null=True, verbose_name='点赞数')),
                ('isHot', models.BooleanField(default=False, verbose_name='是否热搜')),
                ('slug', models.SlugField(default='', max_length=100, verbose_name='子模型名')),
            ],
            options={
                'ordering': ['modify_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='programming',
            options={'verbose_name': '编程', 'verbose_name_plural': '编程'},
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='comment_no',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='like_no',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='project_addr',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='release_person',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='comment_no',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='id',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='like_no',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='release_person',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='title',
        ),
        migrations.RemoveField(
            model_name='software',
            name='comment_no',
        ),
        migrations.RemoveField(
            model_name='software',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='software',
            name='id',
        ),
        migrations.RemoveField(
            model_name='software',
            name='like_no',
        ),
        migrations.RemoveField(
            model_name='software',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='software',
            name='release_person',
        ),
        migrations.RemoveField(
            model_name='software',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='software',
            name='title',
        ),
        migrations.AddField(
            model_name='opensource',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/opensource/cover/%Y/%m', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='type',
            field=models.CharField(choices=[('', ''), ('typeOne', 'typeOne'), ('typeTwo', 'typeTwo')], default='', max_length=10, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='programming',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/programming/cover/%Y/%m', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='opensource',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='programming',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='软件描述'),
        ),
        migrations.AlterField(
            model_name='programming',
            name='type',
            field=models.CharField(choices=[('', ''), ('Java', 'Java'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('JavaScript', 'JavaScript')], default='', max_length=10, verbose_name='编程语言'),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='软件描述'),
        ),
        migrations.AlterField(
            model_name='software',
            name='icon',
            field=models.ImageField(blank=True, default='/media/default_avatar.jpeg', null=True, upload_to='media/software/icon/%Y/%m', verbose_name='软件icon'),
        ),
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.CharField(choices=[('All', 'All'), ('Windows', 'Windows'), ('Android', 'Android'), ('IOS', 'IOS'), ('MAC', 'MAC'), ('Linux', 'Linux')], default='All', max_length=10, verbose_name='软件分类'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post')),
                ('description', mdeditor.fields.MDTextField(verbose_name='详情')),
            ],
            options={
                'verbose_name': '经验',
                'verbose_name_plural': '经验',
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post')),
                ('description', mdeditor.fields.MDTextField(verbose_name='详情')),
            ],
            options={
                'verbose_name': '问答',
                'verbose_name_plural': '问答',
            },
            bases=('posts.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='contribute_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programming',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
    ]
