# Generated by Django 2.0 on 2018-10-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181005_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpensourceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_addr', models.CharField(max_length=100, verbose_name='项目地址')),
                ('description', models.TextField(verbose_name='软件描述')),
            ],
            options={
                'verbose_name': '开源项目详情',
                'verbose_name_plural': '开源项目详情',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Java'), (2, 'Python')], verbose_name='编程语言')),
                ('description', models.TextField(verbose_name='软件描述')),
            ],
            options={
                'verbose_name': '编程详情',
                'verbose_name_plural': '编程详情',
            },
        ),
        migrations.CreateModel(
            name='SoftwareDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/software/icon/%Y/%m', verbose_name='软件icon')),
                ('type', models.IntegerField(choices=[(1, 'Windows'), (2, 'Android'), (3, 'IOS'), (4, 'MAC'), (5, 'Linux')], verbose_name='软件分类')),
                ('description', models.TextField(verbose_name='软件描述')),
            ],
            options={
                'verbose_name': '软件详情',
                'verbose_name_plural': '软件详情',
            },
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='project_addr',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='description',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='type',
        ),
        migrations.RemoveField(
            model_name='software',
            name='description',
        ),
        migrations.RemoveField(
            model_name='software',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='software',
            name='type',
        ),
        migrations.AlterField(
            model_name='software',
            name='contribute_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribute_person', to=settings.AUTH_USER_MODEL, verbose_name='帖子投稿者'),
        ),
        migrations.AlterField(
            model_name='software',
            name='release_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_person', to=settings.AUTH_USER_MODEL, verbose_name='帖子发布者'),
        ),
        migrations.AddField(
            model_name='softwaredetail',
            name='software',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='posts.Software', verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='programmingdetail',
            name='programming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='posts.Programming'),
        ),
        migrations.AddField(
            model_name='opensourcedetail',
            name='opensource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='posts.Opensource'),
        ),
    ]
