# Generated by Django 2.0 on 2018-10-13 10:12

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181009_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensourcedetail',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='软件描述'),
        ),
        migrations.AlterField(
            model_name='programmingdetail',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='软件描述'),
        ),
        migrations.AlterField(
            model_name='softwaredetail',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='软件描述'),
        ),
    ]
