# Generated by Django 2.0 on 2018-11-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181013_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaredetail',
            name='type',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Android', 'Android'), ('IOS', 'IOS'), ('MAC', 'MAC'), ('Linux', 'Linux')], max_length=10, verbose_name='软件分类'),
        ),
    ]
