# Generated by Django 2.0.8 on 2018-12-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181224_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensource',
            name='type',
            field=models.CharField(choices=[('', ''), ('typeOne', 'typeOne'), ('typeTwo', 'typeTwo')], default=None, max_length=10, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(choices=[('opensource', 'opensource'), ('software', 'software'), ('experience', 'experience'), ('program', 'program'), ('question', 'question')], default=None, max_length=100, verbose_name='子模型名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=20, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='programming',
            name='type',
            field=models.CharField(choices=[('', ''), ('Java', 'Java'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('JavaScript', 'JavaScript')], default=None, max_length=10, verbose_name='编程语言'),
        ),
    ]
