# Generated by Django 2.0 on 2018-11-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_comment_comm2hacker'),
        ('posts', '0006_auto_20181126_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hacker',
        ),
        migrations.AddField(
            model_name='programming',
            name='type',
            field=models.CharField(choices=[('', ''), ('Java', 'Java'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('JavaScript', 'JavaScript')], default='', max_length=10, verbose_name='编程语言'),
        ),
    ]
