# Generated by Django 2.0 on 2018-12-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20181129_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingdetail',
            name='type',
        ),
        migrations.AddField(
            model_name='software',
            name='url',
            field=models.CharField(default='/software/details/', max_length=100, verbose_name='软件详情路由'),
        ),
    ]
