# Generated by Django 2.0 on 2018-12-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20181210_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensource',
            name='type',
            field=models.CharField(default='All', max_length=10, verbose_name='分类'),
        ),
    ]
