# Generated by Django 2.0 on 2018-12-14 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='icon',
            field=models.ImageField(default='', upload_to='media/experience/icon/%Y/%m', verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='url',
            field=models.CharField(default='/experience/details/', max_length=100, verbose_name='详情页面路由'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
    ]
