# Generated by Django 2.0 on 2018-12-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20181214_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Programming', verbose_name='编程')),
            ],
            options={
                'verbose_name': 'POST',
                'verbose_name_plural': 'POST',
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='icon',
            field=models.ImageField(upload_to='media/experience/icon/%Y/%m', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='post',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Experience', verbose_name='经验'),
        ),
        migrations.AddField(
            model_name='post',
            name='opensource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Opensource', verbose_name='开源'),
        ),
        migrations.AddField(
            model_name='post',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Software', verbose_name='软件'),
        ),
    ]
