# Generated by Django 2.0 on 2018-12-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20181216_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Programming', verbose_name='编程')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Experience', verbose_name='经验')),
            ],
            options={
                'verbose_name': 'POST',
                'verbose_name_plural': 'POST',
            },
        ),
        migrations.AlterField(
            model_name='opensource',
            name='type',
            field=models.CharField(choices=[('无分类', '无分类'), ('分类一', '分类一'), ('分类二', '分类二')], default='无分类', max_length=10, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='post',
            name='opensource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Opensource', verbose_name='开源'),
        ),
        migrations.AddField(
            model_name='post',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Software', verbose_name='软件'),
        ),
    ]
