# Generated by Django 2.0 on 2018-12-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20181217_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensource',
            name='type',
            field=models.CharField(choices=[('', ''), ('typeOne', 'typeOne'), ('typeTwo', 'typeTwo')], default='', max_length=10, verbose_name='分类'),
        ),
    ]
