# Generated by Django 2.0 on 2018-12-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20181217_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='url',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='url',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='url',
        ),
        migrations.RemoveField(
            model_name='software',
            name='url',
        ),
    ]
