# Generated by Django 2.0 on 2018-12-18 17:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_auto_20181218_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonfields',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='commonfields',
            name='release_person',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programming',
            options={'verbose_name': '编程', 'verbose_name_plural': '编程'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='title',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='commonfields_ptr',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Programming',
        ),
        migrations.RemoveField(
            model_name='post',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='post',
            name='opensource',
        ),
        migrations.RemoveField(
            model_name='post',
            name='software',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='commonfields_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='software',
            name='commonfields_ptr',
        ),
        migrations.AddField(
            model_name='experience',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opensource',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='comment_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='post',
            name='contribute_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribute_person', to=settings.AUTH_USER_MODEL, verbose_name='帖子投稿者'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='post',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间'),
        ),
        migrations.AddField(
            model_name='post',
            name='release_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_person', to=settings.AUTH_USER_MODEL, verbose_name='帖子发布者'),
        ),
        migrations.AddField(
            model_name='post',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='programming',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CommonFields',
        ),
    ]
