# Generated by Django 2.0 on 2018-12-18 20:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_auto_20181218_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='post',
            name='release_person',
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['modify_time'], 'verbose_name': '经验', 'verbose_name_plural': '经验'},
        ),
        migrations.AlterModelOptions(
            name='opensource',
            options={'ordering': ['modify_time'], 'verbose_name': '开源', 'verbose_name_plural': '开源'},
        ),
        migrations.AlterModelOptions(
            name='programming',
            options={'ordering': ['modify_time'], 'verbose_name': '编程', 'verbose_name_plural': '编程'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['modify_time'], 'verbose_name': '问答', 'verbose_name_plural': '问答'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['modify_time'], 'verbose_name': '软件', 'verbose_name_plural': '软件'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='software',
            name='post_ptr',
        ),
        migrations.AddField(
            model_name='experience',
            name='comment_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='experience',
            name='contribute_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='experience',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='like_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='experience',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间'),
        ),
        migrations.AddField(
            model_name='experience',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='comment_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='contribute_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opensource',
            name='like_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='programming',
            name='comment_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='programming',
            name='contribute_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='programming',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programming',
            name='like_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='programming',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间'),
        ),
        migrations.AddField(
            model_name='programming',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='programming',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='question',
            name='comment_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='question',
            name='contribute_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='like_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间'),
        ),
        migrations.AddField(
            model_name='question',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='software',
            name='comment_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='software',
            name='contribute_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='software',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='like_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='software',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间'),
        ),
        migrations.AddField(
            model_name='software',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='software',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='标题'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
