# Generated by Django 2.0 on 2018-12-20 11:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0021_auto_20181218_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('release_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最新修改时间')),
                ('comment_no', models.IntegerField(blank=True, null=True, verbose_name='评论数')),
                ('like_no', models.IntegerField(blank=True, null=True, verbose_name='点赞数')),
                ('contribute_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'ordering': ['modify_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': '经验', 'verbose_name_plural': '经验'},
        ),
        migrations.AlterModelOptions(
            name='opensource',
            options={'verbose_name': '开源', 'verbose_name_plural': '开源'},
        ),
        migrations.AlterModelOptions(
            name='programming',
            options={'verbose_name': '编程', 'verbose_name_plural': '编程'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '问答', 'verbose_name_plural': '问答'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': '软件', 'verbose_name_plural': '软件'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='comment_no',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='like_no',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='title',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='comment_no',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='like_no',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='comment_no',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='id',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='like_no',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='comment_no',
        ),
        migrations.RemoveField(
            model_name='question',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like_no',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.RemoveField(
            model_name='software',
            name='comment_no',
        ),
        migrations.RemoveField(
            model_name='software',
            name='contribute_person',
        ),
        migrations.RemoveField(
            model_name='software',
            name='id',
        ),
        migrations.RemoveField(
            model_name='software',
            name='like_no',
        ),
        migrations.RemoveField(
            model_name='software',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='software',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='software',
            name='title',
        ),
        migrations.AddField(
            model_name='experience',
            name='frontend_url',
            field=models.CharField(default='/experience/detail/', max_length=255, verbose_name='前端url'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='frontend_url',
            field=models.CharField(default='/opsource/detail/', max_length=255, verbose_name='前端url'),
        ),
        migrations.AddField(
            model_name='programming',
            name='frontend_url',
            field=models.CharField(default='/program/detail/', max_length=255, verbose_name='前端url'),
        ),
        migrations.AddField(
            model_name='question',
            name='frontend_url',
            field=models.CharField(default='/question/detail/', max_length=255, verbose_name='前端url'),
        ),
        migrations.AddField(
            model_name='software',
            name='frontend_url',
            field=models.CharField(default='/software/detail/', max_length=255, verbose_name='前端url'),
        ),
        migrations.AddField(
            model_name='experience',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opensource',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programming',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post'),
            preserve_default=False,
        ),
    ]
