# Generated by Django 2.0 on 2018-12-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20181220_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='frontend_url',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='frontend_url',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='frontend_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='frontend_url',
        ),
        migrations.RemoveField(
            model_name='software',
            name='frontend_url',
        ),
        migrations.AddField(
            model_name='post',
            name='frontend_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='前端链接'),
        ),
    ]
