# Generated by Django 2.0 on 2018-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20181220_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='frontend_url',
        ),
        migrations.AddField(
            model_name='post',
            name='isHot',
            field=models.BooleanField(default=False, verbose_name='是否热搜'),
        ),
    ]
