# Generated by Django 2.0 on 2018-12-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20181220_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=models.SlugField(default='experience', max_length=100, verbose_name='模型名'),
        ),
        migrations.AddField(
            model_name='opensource',
            name='slug',
            field=models.SlugField(default='opensource', max_length=100, verbose_name='模型名'),
        ),
        migrations.AddField(
            model_name='programming',
            name='slug',
            field=models.SlugField(default='program', max_length=100, verbose_name='模型名'),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='question', max_length=100, verbose_name='模型名'),
        ),
        migrations.AddField(
            model_name='software',
            name='slug',
            field=models.SlugField(default='software', max_length=100, verbose_name='模型名'),
        ),
    ]
