# Generated by Django 2.0 on 2018-12-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20181221_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='opensource',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='programming',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='software',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='子模型名'),
            preserve_default=False,
        ),
    ]
